#!/usr/bin/env bash


# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [[ ${1} == "" ]]; then
	echo "Usage: ${0} domain"
	exit
fi
DOMAIN=""
TD=${1}
TLD=${1##*.}
while [[ ! "${TD}" == "${TLD}" ]]; do
	DOMAIN=${TD}
	TD=${TD#*.}
done
if [[ ! -d ${DOMAIN} ]]; then
	mkdir ${DOMAIN}
fi

SUBJECT="/CN=${1}/C=US/ST=Mississippi/L=Hattiesburg/O=Foldspace/OU=Foldspace"
openssl req -newkey rsa:4096 -nodes -keyout ${DOMAIN}/${1}.key -new -subj ${SUBJECT} -out ${DOMAIN}/${1}.csr
