#!/usr/bin/env bash


# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [[ ${1} == "" ]]; then
	echo "Usage: ${0} <domain>"
	exit
fi
if [[ ! -f ${1}.crt ]]; then
	echo "Certificate doesn't exist"
	exit
fi
openssl x509 -in ${1}.crt -out ${1}.der -outform DER
