#!/bin/bash


#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ ${#} -lt 2 ]]; then
	echo "Usage: ${0} <domain> <domain> [<domain>...]"
	exit
fi

CRT="${1}"

DOMAIN=""
TD=${1}
TLD=${1##*.}
while [[ ! "${TD}" == "${TLD}" ]]; do
	DOMAIN=${TD}
	TD=${TD#*.}
done

ALT_NAMES="subjectAltName="
while [[ ${#} -gt 1 ]]; do
ALT_NAMES="${ALT_NAMES}DNS:${1},"
shift
done
ALT_NAMES="${ALT_NAMES}DNS:${1}"
if [[ ! -d ${DOMAIN} ]]; then
	mkdir ${DOMAIN}
fi
echo "${ALT_NAMES}" > ${DOMAIN}/${CRT}.cnf
