#!/bin/bash


#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.


DOMAIN=""
TD=${1}
TLD=${1##*.}
while [[ ! "${TD}" == "${TLD}" ]]; do
	DOMAIN=${TD}
	TD=${TD#*.}
done
openssl pkcs12 -export -clcerts -in ${DOMAIN}/${1}.crt -inkey ${DOMAIN}/${1}.key -out ${DOMAIN}/${1}.p12 -name "${1}"
